Started by upstream project "[8mha:////4Lor0SfGRtKHjt862G6e4sQ6+3G0t4D3TXi0qany0iTTAAAAnR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAweoBn6WflJ+i755Xk5+YkpLoklifoA0wQHwccAAAA=[0mDownloadData" build number [8mha:////4IvGdSB0Wrw+Qgjbzqt35qkSHOy8GYrhOSQXhfY+xlfGAAAAoB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAymEgYR/az8JH2X/PK8nPzEFJfEkkR9I0MAXr4CxMkAAAA=[0m21
originally caused by:
 Started by user unknown or anonymous
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/LaunchContainerAndLoadFiles
[LaunchContainerAndLoadFiles] $ /bin/sh -xe /tmp/jenkins2523389504700003613.sh
+ sudo cat /root/MLOps/Python/main.py
+ grep keras
from keras.layers import Dense
+ sudo docker ps
+ grep neuralnetwork
5a246e014a6c        tensorflowimage     "python3"           4 hours ago         Up 4 hours                              neuralnetwork
+ echo 'Already Running'
Already Running
Triggering a new build of [8mha:////4HLPkb5d6hQInvo4Go5q6Q74zyL62OCOVYnJgSiN2x7qAAAAnR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzeEgZh/az8JKDuxKKSkKLEzDygIfoA3hxYH8gAAAA=[0mStartTraining
Finished: SUCCESS
